language: c
os: linux
dist: xenial
sudo: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:vriviere/ppa'
    packages:
      - aranym
      - rpm2cpio
      - uml-utilities
      - binutils-m68k-atari-mint
      - gcc-m68k-atari-mint

env:
  global:
    - BINTRAY_USER="mikrosk"
    # BINTRAY_API_KEY is defined in Travis Settings of m68k-atari-mint/bootstrap

install:
    - sudo ./enable_tun.sh $USER
    - unset CC
    - unset CXX
    - mkdir -p ~/.ssh && ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
    - wget -q -O - https://dl.bintray.com/aranym/aranym-files/snapshots/aranym-1.1.0-trusty-x86_64-e85be35.tar.xz | sudo tar -C /usr/local --strip-components=2 -xJf -

jobs:
  include:
    - stage: Prepare
      script:
        - make prepare shutdown
        - rm drive_d/etc/nologin
        - tar cf drive_d.img drive_d

    - stage: Build1
      name: zlib
      script:
        - ./.travis/download_host_drive.sh Prepare d
        - ./.travis/download_drive.sh Prepare e
        - make prepare_boot configure1 build1 shutdown

    - stage: Build2.1
      name: openssl libs
      script:
        - ./.travis/download_host_drive.sh Prepare d
        - ./.travis/download_drive.sh Build1 e
        - make prepare_boot configure2 build2.1 shutdown

    - stage: Build2.2
      name: openssl
      script:
        - ./.travis/download_host_drive.sh Prepare d
        - ./.travis/download_drive.sh Build2.1 e
        - make prepare_boot build2.2 shutdown

    - stage: Build3
      name: libarchive
      script:
        - ./.travis/download_host_drive.sh Prepare d
        - ./.travis/download_drive.sh Build2.2 e
        - make prepare_boot configure3 build3 shutdown

    - stage: Build4
      name: openssh
      script:
       - ./.travis/download_host_drive.sh Prepare d
       - ./.travis/download_drive.sh Build3 e
       - ./.travis/download_drive.sh Prepare f
       - make prepare_boot configure4 build4 shutdown
       - rm drive_e.img

    - stage: Build5
      name: opkg
      script:
       - ./.travis/download_host_drive.sh Prepare d
       - ./.travis/download_drive.sh Build3 e
       - ./.travis/download_drive.sh Build4 f
       - make prepare_boot configure5 build5 shutdown
       - rm drive_e.img

    - stage: Build6
      name: bash-minimal
      script:
       - ./.travis/download_host_drive.sh Prepare d
       - ./.travis/download_drive.sh Build3 e
       - ./.travis/download_drive.sh Build5 f
       - make prepare_boot configure6 build6 shutdown
       - rm drive_e.img

    - stage: Build7
      name: bash
      script:
       - ./.travis/download_host_drive.sh Prepare d
       - ./.travis/download_drive.sh Build3 e
       - ./.travis/download_drive.sh Build6 f
       - make prepare_boot configure7 build7 shutdown
       - rm drive_e.img

    - stage: Build8
      name: coreutils
      script:
       - ./.travis/download_host_drive.sh Prepare d
       - ./.travis/download_drive.sh Build3 e
       - ./.travis/download_drive.sh Build7 f
       - make prepare_boot configure8 build8 shutdown
       - rm drive_e.img

    # stage 8 can build many packages in parallel

before_deploy:
    - sed -i -e "s/PACKAGE_VERSION/${TRAVIS_COMMIT}/g;" .travis/bintray.desc
    - sed -i -e "s/PACKAGE_STAGE/${TRAVIS_BUILD_STAGE_NAME}/g;" .travis/bintray.desc
    - sed -i -e "s/COMMIT_ID/${TRAVIS_COMMIT}/g;" .travis/bintray.desc
    - sed -i -e "s/COMMIT_URL/https:\/\/github.com\/m68k-atari-mint\/bootstrap\/commit\/${TRAVIS_COMMIT}/g;" .travis/bintray.desc
    - if [ -f drive_d.img ]; then bzip2 drive_d.img; fi
    - if [ -f drive_e.img ]; then bzip2 drive_e.img; fi
    - if [ -f drive_f.img ]; then bzip2 drive_f.img; fi

deploy:
  provider: bintray
  file: ".travis/bintray.desc"
  user: "${BINTRAY_USER}"
  key: "${BINTRAY_API_KEY}"
  skip_cleanup: true
  on:
    branch: master
    repo: m68k-atari-mint/bootstrap
